In [1]:
import numpy as np
from PIL import Image
import os
rootDir = 'photos'
arr = np.zeros([20, 200, 200])
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)
        filepath = dirName+os.sep+fname
        if filepath.endswith('.jpg'):
            print("resized photos")
            img = Image.open(filepath)
            img = img.resize((200,200))
            print(img)
            arr = np.array(img)
            print("3-dimentional array :")
            print(arr)

Found directory: photos
	1.jpg
resized photos
<PIL.Image.Image image mode=RGB size=200x200 at 0x19D17100358>
3-dimentional array :
[[[165 188 202]
  [151 177 178]
  [164 188 200]
  ...
  [ 43  65  18]
  [ 58  85  40]
  [ 21  42   9]]

 [[158 181 199]
  [153 179 176]
  [164 188 200]
  ...
  [ 52  75  23]
  [155 178 172]
  [ 22  42  17]]

 [[165 190 194]
  [164 189 196]
  [164 188 200]
  ...
  [ 50  72  25]
  [157 183 200]
  [ 73  98  41]]

 ...

 [[127 156   2]
  [166 197  15]
  [170 199  11]
  ...
  [ 77 116   1]
  [ 73 115   3]
  [ 95 130   0]]

 [[101 124   0]
  [143 176   9]
  [140 186   0]
  ...
  [ 74 101   4]
  [ 68 109   3]
  [114 141  10]]

 [[ 86 104   0]
  [129 158   4]
  [123 169   0]
  ...
  [ 64  90   1]
  [ 65 106   4]
  [114 137   7]]]
	10.jpg
resized photos
<PIL.Image.Image image mode=RGB size=200x200 at 0x19D17100358>
3-dimentional array :
[[[ 7 10 17]
  [ 7 10 17]
  [ 8 11 18]
  ...
  [ 5  6  8]
  [ 4  5  7]
  [ 6  7  9]]

 [[ 7 10 17]
  [ 7 10 17]
  [ 8 11 18]
  ...
