In [7]:
import numpy as np
from PIL import Image
import os
rootDir='photos'
arr=np.zeros([20,200,200,3])
def main():
    try:
        def num_of_files():
            try:
                for dirname,subdirList,fileList in os.walk(rootDir):
                    file_Count=len(fileList)
                    print("Total No Of file = ",file_Count)
            except FileNotFoundError:
                print("File not found")
        def find_dir():
            try:
                for dirname,subdirList,fileList in os.walk(rootDir):
                    print("Found directory: %s" %dirname)
                    for fname in fileList:
                        print("\t%s"%fname)
            except FileNotFoundError:
                print("File not found")
        def img_resize():
            try:
                i=0
                for dirname,subdirList,fileList in os.walk(rootDir):
                    for fname in fileList:
                        filePath=dirname+os.sep+fname
                        if filePath.endswith('.jpg'):
                            img=Image.open(filePath)
                            img_n=img.resize((200,200))
                            arr[i]=img_n
                            i+=1
                print(arr)
            except FileNotFoundError:
                print("File not found")
        print(num_of_files())
        print(find_dir())
        print("Numpy array of resized image")
        print(img_resize())
    except RuntimeError:
        print("Found an error...!")
if __name__ == '__main__':
    main()
        


Total No Of file =  21
None
Found directory: photos
	1.jpg
	10.jpg
	11.jpg
	12.jpg
	13.jpg
	14.jpg
	15.jpg
	16.jpg
	17.jpg
	18.jpg
	19.jpg
	2.jpg
	20.jpg
	3.jpg
	4.jpg
	5.jpg
	6.jpg
	7.jpg
	8.jpg
	9.jpg
	desktop.ini
None
Numpy array of resized image
[[[[165. 188. 202.]
   [151. 177. 178.]
   [164. 188. 200.]
   ...
   [ 43.  65.  18.]
   [ 58.  85.  40.]
   [ 21.  42.   9.]]

  [[158. 181. 199.]
   [153. 179. 176.]
   [164. 188. 200.]
   ...
   [ 52.  75.  23.]
   [155. 178. 172.]
   [ 22.  42.  17.]]

  [[165. 190. 194.]
   [164. 189. 196.]
   [164. 188. 200.]
   ...
   [ 50.  72.  25.]
   [157. 183. 200.]
   [ 73.  98.  41.]]

  ...

  [[127. 156.   2.]
   [166. 197.  15.]
   [170. 199.  11.]
   ...
   [ 77. 116.   1.]
   [ 73. 115.   3.]
   [ 95. 130.   0.]]

  [[101. 124.   0.]
   [143. 176.   9.]
   [140. 186.   0.]
   ...
   [ 74. 101.   4.]
   [ 68. 109.   3.]
   [114. 141.  10.]]

  [[ 86. 104.   0.]
   [129. 158.   4.]
   [123. 169.   0.]
   ...
   [ 64.  90.   1.]
   [ 65. 10